# Boba

spacing = 1
padding = 1
hide_ascii = true
separator = "->"
key_color = "Cyan"
separator_color = "White"

[palette]
type = "Dark"
glyph = " "
visible = true

[bar]
glyph = "󰆧"
hide_delimiters = true
visible = true

[box]
title = " Fetch 󰗣 "
border = "rounded"
visible = true

[box.inner_margin]
x = 1
y = 1

[randomize]
key_color = true

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distr = "Distro"
terminal = "Terminal"
shel = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "Local IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU Load"
cpu = "CPU"
gpu = "GPU"
disk_space = "Disk Space"
